#!/bin/bash

source ./.devcontainer/.env

docker build -t ${LOCAL_WORKSPACE_FOLDER}/init:latest .devcontainer/docker/init

docker run --name ${LOCAL_WORKSPACE_FOLDER}-init -v ./:/workspace ${LOCAL_WORKSPACE_FOLDER}/init:latest

docker rm ${LOCAL_WORKSPACE_FOLDER}-init
