#!/bin/bash

source ./.devcontainer/.env

echo "Building Liferay Workspace"

docker build -t ${LOCAL_WORKSPACE_FOLDER}/init:latest .devcontainer/docker/init >/dev/null 2>&1

docker run --name ${LOCAL_WORKSPACE_FOLDER}-init -v ./:/workspace ${LOCAL_WORKSPACE_FOLDER}/init:latest

docker rm ${LOCAL_WORKSPACE_FOLDER}-init
